window.MWEMBED_VERSION="1.8.3.1";window.SCRIPT_LOADER_URL="http://cdnapi.kaltura.com/html5/html5lib/v1.8.3.1/load.php";
(function(){if(!window.kWidget){var i={startTime:{},loadTime:{},readyWidgets:{},readyCallbacks:[],destroyedWidgets:{},perWidgetCallback:{},readyCallbackPerWidget:{},listenerList:{},userAgentPlayerRules:{},alreadyAddedThumbRules:!1,iframeAutoEmbedCache:{},setup:function(){var a=this;mw.setConfig("version",MWEMBED_VERSION);this.checkEnvironment();this.overrideFlashEmbedMethods();this.proxyJsCallbackready();this.domReady(function(){a.domIsReady=!0;a.proxyJsCallbackready()});this.domReady(function(){a.rewriteObjectTags()})},
checkEnvironment:function(){document.URL.indexOf("forceMobileHTML5")!==-1&&!mw.getConfig("disableForceMobileHTML5")&&mw.setConfig("forceMobileHTML5",!0);var a=navigator.userAgent,b=a.match(/MSIE\s([0-9]+)/);b&&parseInt(b[1])<9&&mw.setConfig("Kaltura.ForceFlashOnDesktop",!0);a.indexOf("BlackBerry")!=-1&&(mw.setConfig("EmbedPlayer.DisableVideoTagSupport",!0),mw.setConfig("EmbedPlayer.NotPlayableDownloadLink",!0));a.indexOf("Android")!=-1&&mw.setConfig("Kaltura.UseAppleAdaptive",!1);/(iPhone|iPod|iPad)/i.test(a)&&
(/OS [2-4]_\d(_\d)? like Mac OS X/i.test(a)||/CPU like Mac OS X/i.test(a))&&mw.setConfig("Kaltura.UseAppleAdaptive",!1);if(!mw.getConfig("EmbedPlayer.IsIframeServer")&&(mw.setConfig("EmbedPlayer.IframeParentUrl",document.URL),mw.setConfig("EmbedPlayer.IframeParentTitle",document.title),mw.setConfig("EmbedPlayer.IframeParentReferrer",document.referrer),/iphone|ipod|ipad.*os 5/gi.test(navigator.appVersion)))window.onpageshow=function(a){if(a.persisted)document.body.style.display="none",location.reload()}},
proxiedJsCallback:null,waitForLibraryChecks:!0,jsReadyCalledForIds:[],proxyJsCallbackready:function(){var a=this,b=function(b){a.waitForLibraryChecks?a.jsReadyCalledForIds.push(b):a.jsCallbackReady(b)};if(!this.proxiedJsCallback)this.proxiedJsCallback=window.jsCallbackReady||!0,window.jsCallbackReady=b;if(window.jsCallbackReady.toString()!=b.toString())this.proxiedJsCallback=window.jsCallbackReady,window.jsCallbackReady=b},jsCallbackReady:function(a){var b=this;if(!this.destroyedWidgets[a]){var c=
document.getElementById(a);if(c){this.extendJsListener(c);var d=c.evaluate("{playerStatusProxy.kdpVersion}");mw.versionIsAtLeast("v3.7.0",d)&&c.kBind("kdpReady",function(){b.loadTime[a]=(((new Date).getTime()-b.startTime[a])/1E3).toFixed(2);c.setKDPAttribute("playerStatusProxy","loadTime",b.loadTime[a])});typeof this.proxiedJsCallback=="function"&&this.proxiedJsCallback(a);for(d=0;d<this.readyCallbacks.length;d++)this.readyCallbacks[d](a);this.readyWidgets[a]=!0}else this.log("Error:: jsCallbackReady called on invalid player Id:"+
a)}},playerModeChecksDone:function(){this.waitForLibraryChecks=!1;for(var a=0;a<this.jsReadyCalledForIds.length;a++)this.jsCallbackReady(this.jsReadyCalledForIds[a]);this.jsReadyCalledForIds=[]},embed:function(a,b){function c(a){b[a]&&(parseInt(b[a])==b[a]&&(b[a]+="px"),g.style[a]=b[a])}var d=this;if(typeof a==="object")b=a,b.targetId||this.log("Error: Missing target element Id"),a=b.targetId;this.startTime[a]=(new Date).getTime();if(b.wid){var e=b.uiconf_id;if(e){var g=document.getElementById(a);
if(!g)return this.log("Error: kWidget.embed could not find target: "+a),!1;if(g.getAttribute("name")!="kaltura_player_iframe_no_rewrite")if(g.innerHTML="",c("width"),c("height"),this.destroyedWidgets[a]&&delete this.destroyedWidgets[a],mw.getConfig("Kaltura.ForceIframeEmbed")===!0)this.outputIframeWithoutApi(a,b);else{if(b.readyCallback){var h=!this.perWidgetCallback[a];this.perWidgetCallback[a]=b.readyCallback;h&&this.addReadyCallback(function(b){if(b==a&&d.perWidgetCallback[b])d.perWidgetCallback[b](b)})}this.proxyJsCallbackready();
b.isHTML5=this.isUiConfIdHTML5(e);this.loadUiConfJs([{kEmbedSettings:b}],function(){d.proxyJsCallbackready();a:{if(e&&d.userAgentPlayerRules&&d.userAgentPlayerRules[e]){var c=d.checkUserAgentPlayerRules(d.userAgentPlayerRules[e]);switch(c.mode){case "flash":if(g.nodeName.toLowerCase()=="object")break a;break;case "leadWithHTML5":b.isHTML5=d.supportsHTML5();break;case "forceMsg":c=c.val;if(g&&g.parentNode){var h=document.createElement("div");h.innerHTML=unescape(c);g.parentNode.replaceChild(h,g)}break a}}b.isHTML5?
d.outputHTML5Iframe(a,b):d.outputFlashObject(a,b)}})}}else this.log("Error: kWidget.embed missing uiconf_id")}else this.log("Error: kWidget.embed missing wid")},addThumbCssRules:function(){if(!this.alreadyAddedThumbRules){this.alreadyAddedThumbRules=!0;var a=document.createElement("STYLE");a.type="text/css";var b=this.getPath()+"/modules/MwEmbedSupport/skins/common/images/",b=".kWidgetCentered {max-height: 100%; max-width: 100%; position: absolute; top: 0; left: 0; right: 0; bottom: 0; margin: auto; } \n.kWidgetPlayBtn { cursor:pointer;height: 53px;width: 70px;top: 50%; left: 50%; margin-top: -26.5px; margin-left: -35px; background: url('"+
b+"player_big_play_button.png');z-index: 1;} \n.kWidgetPlayBtn:hover{ background: url('"+b+"player_big_play_button_hover.png');\"} ";this.isIE()?a.styleSheet.cssText=b:a.innerHTML=b;document.getElementsByTagName("HEAD")[0].appendChild(a)}},getComputedSize:function(a,b){var c=navigator.userAgent;return c.indexOf("msie")!=-1&&c.indexOf("opera")==-1?document.getElementById(theElt)["offset"+b[0].toUpperCase()+b.substr(1)]:parseInt(document.defaultView.getComputedStyle(a,"").getPropertyValue(b))},thumbEmbed:function(a,
b){typeof a==="object"?(b=a,b.targetId||this.log("Error: Missing target element Id"),a=b.targetId):b.targetId=a;this.addThumbCssRules();var c=document.getElementById(a);c||this.log("Error could not find target id, for thumbEmbed");c.innerHTML='<div style="position: relative; width: 100%; height: 100%;"><img class="kWidgetCentered" src="'+this.getKalturaThumbUrl(b)+'" ><div class="kWidgetCentered kWidgetPlayBtn" id="'+a+'_playBtn"></div></div>';this.addEvent(document.getElementById(a+"_playBtn"),"click",
function(){if(b.readyCallback)var a=b.readyCallback;b.readyCallback=function(b){var c=document.getElementById(b);c.kBind("mediaReady",function(){c.sendNotification("doPlay")});typeof a=="function"&&a(b)};b.captureClickEventForiOS=!0;i.embed(b)});b.thumbReadyCallback&&b.thumbReadyCallback(a)},destroy:function(a){typeof a=="string"&&(a=document.getElementById(a));if(a){var b=a.id,c=a.style.cssText,d=a.className,e=a.getAttribute("id"),g;for(g in this.readyWidgets)g==e&&delete this.readyWidgets[g];this.destroyedWidgets[e]=
!0;e=document.createElement("div");e.style.cssText=c;e.id=b;e.className=d;a.parentNode.replaceChild(e,a)}else this.log("Error destory called without valid target")},embedFromObjects:function(a){for(var b=0;b<a.length;b++){var c=a[b].kEmbedSettings;c.width=a[b].width;c.height=a[b].height;this.embed(a[b].id,a[b].kEmbedSettings)}},extendJsListener:function(a){var b=this;a.kBind=function(c,d){var e=0,g="",h=this;if(typeof c=="string")var j=c.split(".",2),k=j[1]?j[1]:"kWidget",c=j[0];if(typeof d=="string")g=
d;else if(typeof d=="function"){var o=function(){g="kWidget_"+c+"_cb"+e;window[g]&&(e++,o())};o();window[g]=function(){var a=Array.prototype.slice.call(arguments,0);d.apply(h,a)}}else{i.log("Error: kWidget : bad callback type: "+d);return}b.listenerList[k]||(b.listenerList[k]={});b.listenerList[k][c]||(b.listenerList[k][c]=g);a.addJsListener(c,g);return a};a.kUnbind=function(c,d){if(typeof c=="string"){var e=c.split(".",2),g=e[1],c=e[0];if(g){for(var h in b.listenerList[g])c?h==c&&(a.removeJsListener(h,
b.listenerList[g][h]),delete b.listenerList[g][h]):a.removeJsListener(h,b.listenerList[g][h]);b.listenerList[g]=null}else for(g in(e=typeof d=="string")&&a.removeJsListener(c,d),b.listenerList)for(h in b.listenerList[g])h==c&&(e||a.removeJsListener(c,b.listenerList[g][h]),delete b.listenerList[g][h])}return a}},outputFlashObject:function(a,b){var c=document.getElementById(a);if(!c&&!c.parentNode)i.log("Error embed target missing");else{if(!b.src){var d=mw.getConfig("Kaltura.ServiceUrl")+"/index.php/kwidget/wid/"+
b.wid+"/uiconf_id/"+b.uiconf_id;b.entry_id&&(d+="/entry_id/"+b.entry_id);b.cache_st&&(d+="/cache_st/"+b.cache_st);b.src=d}b.id=c.id;c.setAttribute("id",c.id+"_container");var e=document.createElement("span");if(!b.flashvars)b.flashvars={};b.flashvars.jsCallbackReadyFunc&&i.log("Error: Setting jsCallbackReadyFunc is not compatible with kWidget embed");var d=this.flashVarsToString(b.flashvars),g={allowFullScreen:"true",allowNetworking:"all",allowScriptAccess:"always",bgcolor:"#000000"},h='<object style="'+
c.style.cssText.replace(/^\s+|\s+$/g,"")+';display:block;"  class="'+c.className+'"  id="'+a+'" name="'+a+'"';h+=' data="'+b.src+'" type="application/x-shockwave-flash"';window.ActiveXObject&&(h+=' classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"');h+=">";h+='<param name="movie" value="'+b.src+'" />';h+='<param name="flashvars" value="'+d+'" />';if(b.params)for(var j in b.params)g[j]?g[j]=b.params[j]:h+='<param name="'+j+'" value="'+b.params[j]+'" />';for(j in g)g[j]&&(h+='<param name="'+j+'" value="'+
g[j]+'" />');h+="</object>";var k=function(){c.parentNode.replaceChild(e,c);e.innerHTML=h};window.console&&(window.console.firebug||window.console.exception)?(console.log("Warning firebug + firefox and dynamic flash kdp embed causes lockups in firefox, ( delaying embed )"),this.domReady(function(){setTimeout(function(){k()},2E3)})):navigator.userAgent.indexOf("MSIE")!=-1?setTimeout(function(){k()},0):k()}},outputHTML5Iframe:function(a,b){var c=document.getElementById(a),d=c.id+"_ifp",e="border:0px; max-width: 100%; max-height: 100%; "+
c.style.cssText,g=document.createElement("iframe");g.id=d;g.scrolling="no";g.name=d;g.className="mwEmbedKalturaIframe";g.allowfullscreen="yes";g.style.cssText=e;if(b.width=="%"||b.height=="%"||c.style.width.indexOf("%")!=-1||c.style.height.indexOf("%")!=-1)d=c.getBoundingClientRect(),g.style.width=d.width+"px",g.style.height=d.height+"px";else{if(b.width)g.width=b.width;if(b.height)g.height=b.height}var h=document.createElement("div");h.id=c.id;h.name=c.name;h.className="kWidgetIframeContainer"+(c.className?
" "+c.className:"");h.style.cssText=c.style.cssText+";overflow: hidden";h.appendChild(g);c.parentNode.replaceChild(h,c);var j=function(){setTimeout(function(){var a=typeof h.getBoundingClientRect=="function"?h.getBoundingClientRect():{width:h.offsetWidth,height:h.offsetHeight};g.style.width=a.width+"px";g.style.height=a.height+"px"},0)};h.parentNode.onresize=j;this.addEvent(window,"resize",j);this.addEvent(window,"orientationchange",j,!0);if(b.captureClickEventForiOS&&(this.isIOS()||this.isAndroid()))this.captureClickWrapedIframeUpdate(a,
b,g);else{var i=this.getIframeCbName(a);window[i]=function(a){var b=g.contentWindow.document;b.open();b.write(a.content);b.close();window[i]=null;j()};if(this.iframeAutoEmbedCache[a])window[i](this.iframeAutoEmbedCache[a]);else this.appendScriptUrl(this.getIframeUrl()+"?"+this.getIframeRequest(c,b)+"&callback="+i)}},getIframeCbName:function(a){for(var b=0,a="mwi_"+a.replace(/[^0-9a-zA-Z]/g,""),c=a+b;window[c];)this.log("Warning: iframe callback already defined: "+c),b++,c=a+b;return c},captureClickWrapedIframeUpdate:function(a,
b,c){var d=document.getElementById(a),e=c.contentDocument;e.open();e.write('<html><head></head><body><div class="mwPlayerContainer"  style="width: 100%; height: 100%"><div class="videoHolder"><video class="persistentNativePlayer" id="'+a+'" kwidgetid="'+b.wid+'" kentryid="'+b.entry_id+'" kuiconfid="'+b.uiconf_id+'" src="'+(location.protocol+"//www.kaltura.com/p/243342/sp/24334200/playManifest/entryId/1_vp5cng42/flavorId/1_6wf0o9n7/format/url/protocol/http/a.mp4")+'" style="width:100%;height:100%" ></video></div></div><script>document.getElementById(\''+
a+'\').play();<\/script><div id="scriptsHolder"></div></body></html>');e.close();a=this.getIframeCbName(a);window[a]=function(a){(c.contentDocument.getElementsByTagName("head")[0]||c.documentElement).innerHTML=a.rawHead;c.contentDocument.getElementById("scriptsHolder").innerHTML=a.rawScripts;for(var a=function(a){var b=a.text||a.textContent||a.innerHTML||"",d=c.contentDocument.getElementsByTagName("head")[0]||c.documentElement,e=c.contentDocument.createElement("script");e.type="text/javascript";e.appendChild(document.createTextNode(b));
d.insertBefore(e,d.firstChild);a.parentNode&&a.parentNode.removeChild(a)},b=[],d=c.contentDocument.getElementById("scriptsHolder").childNodes,e=0;d[e];e++)if(b&&d[e].nodeName&&d[e].nodeName.toUpperCase()==="SCRIPT"&&(!d[e].type||d[e].type.toLowerCase()==="text/javascript"))b.push(d[e].parentNode?d[e].parentNode.removeChild(d[e]):d[e]);for(var i in b)a(b[i])};this.appendScriptUrl(this.getIframeUrl()+"?"+this.getIframeRequest(d,b)+"&callback="+a+"&parts=1")},getIframeRequest:function(a,b){var c=this.embedSettingsToUrl(b);
c+="&playerId="+a.id;mw.getConfig("debug")&&(c+="&debug=true");mw.getConfig("Kaltura.KWidgetPsPath")&&(c+="&pskwidgetpath="+mw.getConfig("Kaltura.KWidgetPsPath"));mw.getConfig("Kaltura.AllowIframeRemoteService")&&mw.getConfig("Kaltura.ServiceUrl").indexOf("kaltura.com")===-1&&mw.getConfig("Kaltura.ServiceUrl").indexOf("kaltura.org")===-1&&(c+=i.serviceConfigToUrl());mw.getConfig("Kaltura.NoApiCache")&&(c+="&nocache=true");this.isUiConfIdHTML5(b.uiconf_id)&&(c+="&forceMobileHTML5=true");c+="&urid="+
MWEMBED_VERSION;return c},getIframeUrl:function(){var a=this.getPath();mw.getConfig("Kaltura.ForceIframeEmbed")===!0&&(a=a.replace("localhost","127.0.0.1"));return a+"mwEmbedFrame.php"},getPath:function(){return SCRIPT_LOADER_URL.replace("load.php","")},outputIframeWithoutApi:function(a,b){var c=document.getElementById(a),c=this.getIframeUrl()+"?"+this.getIframeRequest(c,b)+"&iframeembed=true",d=document.getElementById(a),e=d.parentNode,g=document.createElement("iframe");g.src=c;g.id=a;g.width=b.width?
b.width.replace(/px/,""):"100%";g.height=b.height?b.height.replace(/px/,""):"100%";g.className=d.className?" "+d.className:"";g.style.cssText=d.style.cssText;g.style.border="0px";g.style.overflow="hidden";e.replaceChild(g,d)},addReadyCallback:function(a){for(var b in this.readyWidgets)document.getElementById(b)&&a(b);this.readyCallbacks.push(a);this.proxyJsCallbackready()},rewriteObjectTags:function(){var a=this.getKalutaObjectList(),b=this;if(this.isMissingUiConfJs(a))this.loadUiConfJs(a,function(){b.rewriteObjectTags()});
else{var c=mw.getConfig("Kaltura.ServiceUrl");if(!mw.getConfig("Kaltura.AllowIframeRemoteService")&&(!c||c.indexOf("kaltura.com")===-1))mw.setConfig("Kaltura.IframeRewrite",!1),mw.setConfig("Kaltura.UseManifestUrls",!1);this.isHTML5FallForward()&&a.length?this.embedFromObjects(a):!this.supportsFlash()&&!this.supportsHTML5()&&!mw.getConfig("Kaltura.ForceFlashOnDesktop")?this.embedFromObjects(a):this.playerModeChecksDone()}},uiConfScriptLoadList:{},inLoaderUiConfJsDone:!1,inLoaderUiConfJsCallbackSet:[],
inLoaderUiConfJsCallback:function(){for(this.inLoaderUiConfJsDone=!0;this.inLoaderUiConfJsCallbackSet.length;)this.inLoaderUiConfJsCallbackSet.shift()()},isMissingUiConfJs:function(a){if(this.inLoaderUiConfJsDone==!1)return!0;if(a.length==0||!mw.getConfig("Kaltura.EnableEmbedUiConfJs")||mw.getConfig("EmbedPlayer.IsIframeServer"))return!1;for(var b=0;b<a.length;b++)if(!this.uiConfScriptLoadList[a[b].kEmbedSettings.uiconf_id])return!0;return!1},uiConfScriptLoadListCallbacks:{},loadUiConfJs:function(a,
b){var c=this,d=function(){c.inLoaderUiConfJsDone?b():c.inLoaderUiConfJsCallbackSet.push(b)},e=this.getPath()+"services.php?service=uiconfJs";mw.getConfig("Kaltura.KWidgetPsPath")&&(e+="&pskwidgetpath="+mw.getConfig("Kaltura.KWidgetPsPath"));if(this.isMissingUiConfJs(a)){for(var g=!1,h=0;h<a.length;h++)(function(a){if(!c.uiConfScriptLoadList[a.uiconf_id]){g=!0;var b="kUiConfJs_"+h+"_"+a.uiconf_id;c.uiConfScriptLoadListCallbacks[b]?c.uiConfScriptLoadListCallbacks[b].push(d):(c.uiConfScriptLoadListCallbacks[b]=
[d],window[b]=function(){c.uiConfScriptLoadList[a.uiconf_id]=!0;$.each(c.uiConfScriptLoadListCallbacks[b],function(a,b){b()})},c.appendScriptUrl(e+c.embedSettingsToUrl(a)+"&callback="+b))}})(a[h].kEmbedSettings);g||d()}else d()},log:function(a){typeof console!="undefined"&&console.log&&console.log(a)},supportsHTML5:function(){if(mw.getConfig("EmbedPlayer.DisableVideoTagSupport"))return!1;var a=document.createElement("video");return navigator.userAgent.indexOf("MSIE 9.")!=-1?!1:a.canPlayType?!0:!1},
supportsFlash:function(){return mw.getConfig("EmbedPlayer.DisableHTML5FlashFallback")?!1:this.getFlashVersion().split(",").shift()<10?!1:!0},getFlashVersion:function(){if(navigator.plugins&&navigator.plugins.length)try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(a){}try{try{if(typeof ActiveXObject!="undefined"){var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
try{b.AllowScriptAccess="always"}catch(c){return"6,0,0"}}}catch(d){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(e){}return"0,0,0"},isIOS:function(){return navigator.userAgent.indexOf("iPhone")!=-1||navigator.userAgent.indexOf("iPod")!=-1||navigator.userAgent.indexOf("iPad")!=-1},isIE:function(){return/\bMSIE\b/.test(navigator.userAgent)},isAndroid:function(){return navigator.userAgent.indexOf("Android ")!=-1},
isUiConfIdHTML5:function(a){var b=this.isHTML5FallForward();this.userAgentPlayerRules&&this.userAgentPlayerRules[a]&&this.checkUserAgentPlayerRules(this.userAgentPlayerRules[a]).mode=="leadWithHTML5"&&(b=this.supportsHTML5());return b},isHTML5FallForward:function(){return this.isIOS()||mw.getConfig("forceMobileHTML5")?!0:(mw.getConfig("KalturaSupport.LeadWithHTML5")||mw.getConfig("Kaltura.LeadWithHTML5"))&&this.supportsHTML5()?!0:this.isAndroid()?mw.getConfig("EmbedPlayer.UseFlashOnAndroid")&&i.supportsFlash()?
!1:!0:i.supportsFlash()?!1:mw.getConfig("Kaltura.ForceFlashOnIE10")&&navigator.userAgent.match(/MSIE\s10/)?!1:mw.getConfig("Kaltura.ForceFlashOnDesktop")?!1:i.supportsHTML5()?!0:mw.getConfig("Kaltura.IframeRewrite")?!0:!1},getKalturaThumbUrl:function(a){var b="";a.width!="100%"&&a.width&&(b+="/width/"+parseInt(a.width));a.height!="100%"&&a.height&&(b+="/height/"+parseInt(a.height));!a.height&&!a.width&&(b+="/height/480");var c="";a.vid_sec&&(c+="/vid_sec/"+a.vid_sec);a.vid_slices&&(c+="/vid_slices/"+
a.vid_slices);var d=a.ks?"?ks="+a.ks:"";if(a.p&&!a.partner_id)a.partner_id=a.p;if(!a.partner_id&&a.wid)a.partner_id=a.wid.replace("_","");var e=a.sp?a.sp:a.partner_id;return this.getPath()+"modules/KalturaSupport/thumbnail.php/p/"+a.partner_id+"/sp/"+e+"/entry_id/"+a.entry_id+"/uiconf_id/"+a.uiconf_id+b+c+d},getEmbedSettings:function(a,b){var c={};typeof b=="string"&&(b=this.flashVars2Object(b));b||(b={});if(!a)return{};c.flashvars=b;for(var d=a.split("/"),e=null;d.length;){var g=d.pop();switch(g){case "p":c.wid=
"_"+e;c.p=e;break;case "wid":c.wid=e;c.p=e.replace(/_/,"");break;case "entry_id":c.entry_id=e;break;case "uiconf_id":case "ui_conf_id":c.uiconf_id=e;break;case "cache_st":c.cache_st=e}e=g.replace(/^\s+|\s+$/g,"")}for(var h in b){d=b[h];h=h.toLowerCase();if(h=="entryid")c.entry_id=d;if(h=="uiconfid")c.uiconf_id=d;if(h=="widgetid"||h=="widget_id")c.wid=d;if(h=="partnerid"||h=="partner_id")c.wid="_"+d,c.p=d;if(h=="referenceid")c.reference_id=d}if(!c.cache_st)c.cache_st=1;return c},flashVars2Object:function(a){for(var a=
a?a.split("&"):[],b={},c=0;c<a.length;c++){var d=a[c].split("=");d[0]&&d[1]&&(b[d[0]]=d[1])}return b},flashVarsToString:function(a){var b="",c;for(c in a)if(typeof a[c]=="object")for(var d in a[c])b+="&"+encodeURIComponent(c)+"."+encodeURIComponent(d)+"="+encodeURIComponent(a[c][d]);else b+="&"+encodeURIComponent(c)+"="+encodeURIComponent(a[c]);return b},flashVarsToUrl:function(a){var b="",c;for(c in a){var d=typeof a[c]=="object"?JSON.stringify(a[c]):a[c];b+="&flashvars["+encodeURIComponent(c)+"]="+
encodeURIComponent(d)}return b},pageHasAudioOrVideoTags:function(){return mw.getConfig("EmbedPlayer.RewriteSelector")===!1||mw.getConfig("EmbedPlayer.RewriteSelector")==""?!1:document.getElementsByTagName("video").length!=0||document.getElementsByTagName("audio").length!=0?!0:!1},getKalutaObjectList:function(){var a=this,b=[],c=document.getElementsByTagName("object");!c.length&&document.getElementById("kaltura_player")&&(c=[document.getElementById("kaltura_player")]);for(var d=function(d,g){var h=
a.getEmbedSettings(d,g);return h&&h.uiconf_id&&h.wid?(c[e].kEmbedSettings=h,b.push(c[e]),!0):!1},e=0;e<c.length;e++)if(c[e]){for(var g="",h={},i=c[e].getElementsByTagName("param"),k=0;k<i.length;k++){var o=i[k].getAttribute("name").toLowerCase(),s=i[k].getAttribute("value");if(o=="data"||o=="src"||o=="movie")g=s;o=="flashvars"&&(h=this.flashVars2Object(s))}d(g,h)||c[e].getAttribute("data")&&d(c[e].getAttribute("data"),h)}return b},jQueryLoadCheck:function(a){window.jQuery?a(window.jQuery):this.appendScriptUrl(this.getPath()+
"resources/jquery/jquery.min.js",function(){a(window.jQuery)})},appendScriptUrls:function(a,b){var c=this,d=0;if(a.length==0)b&&b();else for(var e=0;e<a.length;e++)(function(e){c.appendScriptUrl(a[e],function(){d++;d==a.length&&b&&b()})})(e)},appendScriptUrl:function(a,b,c){c||(c=document);var d=c.getElementsByTagName("head")[0]||c.documentElement,e=c.createElement("script");e.src=a;var g=!1;e.onload=e.onreadystatechange=function(){if(!g&&(!this.readyState||this.readyState==="loaded"||this.readyState===
"complete"))g=!0,typeof b=="function"&&b(),e.onload=e.onreadystatechange=null,d&&e.parentNode&&d.removeChild(e)};d.insertBefore(e,d.firstChild)},appendCssUrl:function(a){var b=document.getElementsByTagName("head")[0],c=document.createElement("link");c.type="text/css";c.rel="stylesheet";c.media="screen";c.href=a;b.appendChild(c)},serviceConfigToUrl:function(){for(var a=["ServiceUrl","CdnUrl","ServiceBase","UseManifestUrls"],b="",c=0;c<a.length;c++)mw.getConfig("Kaltura."+a[c])!==null&&(b+="&"+a[c]+
"="+encodeURIComponent(mw.getConfig("Kaltura."+a[c])));return b},addEvent:function(a,b,c,d){a.attachEvent?(a["e"+b+c]=c,a[b+c]=function(){a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c])):a.addEventListener(b,c,!!d)},removeEvent:function(a,b,c){a.detachEvent?(a.detachEvent("on"+b,a[b+c]),a[b+c]=null):a.removeEventListener(b,c,!1)},isEmptyObject:function(a){for(var b in a)return!1;return!0},embedSettingsToUrl:function(a){var b="",c=["uiconf_id","entry_id","wid","p","cache_st"],d;for(d in a)for(var e=
0;e<c.length;e++)c[e]==d&&(b+="&"+d+"="+encodeURIComponent(a[d]));b+=this.flashVarsToUrl(a.flashvars);return b},overrideFlashEmbedMethods:function(){var a=this,b=function(a,b,c,d){if(c)a.width=c;if(d)a.height=d;i.embed(b,a)};if(window.flashembed&&!window.originalFlashembed){window.originalFlashembed=window.flashembed;window.flashembed=function(c,d,h){a.domReady(function(){var a=i.getEmbedSettings(d.src,h);if(a.uiconf_id&&(i.isHTML5FallForward()||!i.supportsFlash()))document.getElementById(c).innerHTML=
'<div style="width:100%;height:100%" id="'+d.id+'"></div>',b(a,d.id,d.width,d.height);else return originalFlashembed(c,d,h)})};for(var c=["asString","getHTML","getVersion","isSupported"],d=0;d<c.length;d++)window.flashembed[c[d]]=originalFlashembed}if(window.SWFObject&&!window.SWFObject.prototype.originalWrite)window.SWFObject.prototype.originalWrite=window.SWFObject.prototype.write,window.SWFObject.prototype.write=function(c){var d=this;a.domReady(function(){var a=i.getEmbedSettings(d.attributes.swf,
d.params.flashVars);a.uiconf_id&&(i.isHTML5FallForward()||!i.supportsFlash())?b(a,c,d.attributes.width,d.attributes.height):d.originalWrite(c)})};if(window.swfobject&&!window.swfobject.originalEmbedSWF)window.swfobject.originalEmbedSWF=window.swfobject.embedSWF,window.swfobject.embedSWF=function(c,d,h,j,k,o,s,D,n,r){a.domReady(function(){var a=i.getEmbedSettings(c,s);a.uiconf_id&&(i.isHTML5FallForward()||!i.supportsFlash())?b(a,d,h,j):window.swfobject.originalEmbedSWF(c,d,h,j,k,o,s,D,n,r)})}}};window.KWidget=
i;window.kWidget=i}})();if(!this.JSON)this.JSON={};
(function(){function i(a){return a<10?"0"+a:a}function a(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var b=h[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(c,d){var h,i,n,r,x=e,p,l=d[c];l&&typeof l==="object"&&typeof l.toJSON==="function"&&(l=l.toJSON(c));typeof j==="function"&&(l=j.call(d,c,l));switch(typeof l){case "string":return a(l);case "number":return isFinite(l)?String(l):"null";case "boolean":case "null":return String(l);
case "object":if(!l)return"null";e+=g;p=[];if(Object.prototype.toString.apply(l)==="[object Array]"){r=l.length;for(h=0;h<r;h+=1)p[h]=b(h,l)||"null";n=p.length===0?"[]":e?"[\n"+e+p.join(",\n"+e)+"\n"+x+"]":"["+p.join(",")+"]";e=x;return n}if(j&&typeof j==="object"){r=j.length;for(h=0;h<r;h+=1)i=j[h],typeof i==="string"&&(n=b(i,l))&&p.push(a(i)+(e?": ":":")+n)}else for(i in l)Object.hasOwnProperty.call(l,i)&&(n=b(i,l))&&p.push(a(i)+(e?": ":":")+n);n=p.length===0?"{}":e?"{\n"+e+p.join(",\n"+e)+"\n"+
x+"}":"{"+p.join(",")+"}";e=x;return n}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+i(this.getUTCMonth()+1)+"-"+i(this.getUTCDate())+"T"+i(this.getUTCHours())+":"+i(this.getUTCMinutes())+":"+i(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var c=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,g,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,c,d){var h;g=e="";if(typeof d==="number")for(h=0;h<d;h+=1)g+=" ";else typeof d==="string"&&(g=d);if((j=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return b("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function d(a,c){var e,h,g=a[c];if(g&&typeof g==="object")for(e in g)Object.hasOwnProperty.call(g,e)&&(h=d(g,e),h!==void 0?g[e]=h:delete g[e]);return b.call(a,c,g)}var e;c.lastIndex=0;c.test(a)&&(a=a.replace(c,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?d({"":e},""):e;throw new SyntaxError("JSON.parse");}})();
(function(i,a){a.deprecatedGlobals=function(){var b={kIsIOS:"isIOS",kSupportsHTML5:"supportsHTML5",kGetFlashVersion:"getFlashVersion",kSupportsFlash:"supportsFlash",kalturaIframeEmbed:"embed",kOutputFlashObject:"outputFlashObject",kIsHTML5FallForward:"isHTML5FallForward",kIframeWithoutApi:"outputIframeWithoutApi",kDirectDownloadFallback:"outputDirectDownload",kGetKalturaEmbedSettings:"getEmbedSetting",kGetKalturaPlayerList:"getKalutaObjectList",kCheckAddScript:"rewriteObjectTags",kAddScript:"loadHTML5Lib",
kPageHasAudioOrVideoTags:"pageHasAudioOrVideoTags",kLoadJsRequestSet:"loadRequestSet",kOverideJsFlashEmbed:"overrideFlashEmbedMethods",kDoIframeRewriteList:"embedFromObjects",kEmbedSettingsToUrl:"embedSettingsToUrl",kGetAdditionalTargetCss:"getAdditionalTargetCss",kAppendCssUrl:"appendCssUrl",kAppendScriptUrl:"appendScriptUrl",kFlashVars2Object:"flashVars2Object",kFlashVarsToUrl:"flashVarsToUrl",kFlashVarsToString:"flashVarsToString",kServiceConfigToUrl:"serviceConfigToUrl",kRunMwDomReady:"rewriteObjectTags",
restoreKalturaKDPCallback:!1},c;for(c in b)(function(c){window[c]=function(){if(b[c]===!1)a.log(c+" is deprecated. This method no longer serves any purpose.");else{a.log(c+" is deprecated. Please use kWidget."+b[c]);var e=Array.prototype.slice.call(arguments,0);if(typeof a[b[c]]!="function")a.log("Error kWidget missing method: "+b[c]);else return a[b[c]].apply(a,e)}}})(c)};a.deprecatedGlobals()})(window.mw,window.kWidget);
(function(i){function a(){if(!j&&(j=!0,k)){for(var a=0;a<k.length;a++)k[a].call(window,[]);k=[]}}function b(a){var b=window.onload;window.onload=typeof window.onload!="function"?a:function(){b&&b();a()}}function c(){if(!h){h=!0;document.addEventListener&&!g.opera&&document.addEventListener("DOMContentLoaded",a,!1);g.msie&&window==top&&function(){if(!j){try{document.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}a()}}();g.opera&&document.addEventListener("DOMContentLoaded",
function(){if(!j){for(var b=0;b<document.styleSheets.length;b++)if(document.styleSheets[b].disabled){setTimeout(arguments.callee,0);return}a()}},!1);if(g.safari){var c;(function(){if(!j)if(document.readyState!="loaded"&&document.readyState!="complete")setTimeout(arguments.callee,0);else{if(c===void 0){for(var b=document.getElementsByTagName("link"),d=0;d<b.length;d++)b[d].getAttribute("rel")=="stylesheet"&&c++;b=document.getElementsByTagName("style");c+=b.length}document.styleSheets.length!=c?setTimeout(arguments.callee,
0):a()}})()}b(a)}}var d=window.DomReady={},e=navigator.userAgent.toLowerCase(),g={version:(e.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],safari:/webkit/.test(e),opera:/opera/.test(e),msie:/msie/.test(e)&&!/opera/.test(e),mozilla:/mozilla/.test(e)&&!/(compatible|webkit)/.test(e)},h=!1,j=!1,k=[];d.ready=function(a){c();j||/loaded|complete/.test(document.readyState)?a.call(window,[]):k.push(function(){return a.call(window,[])})};c();i.domReady=d.ready})(window.kWidget);
var logIfInIframe=typeof preMwEmbedConfig!="undefined"&&preMwEmbedConfig["EmbedPlayer.IsIframeServer"]?" ( iframe ) ":"";kWidget.log("Kaltura HTML5 Version: "+MWEMBED_VERSION+logIfInIframe);window.mw||(window.mw={});if(!window.preMwEmbedReady)window.preMwEmbedReady=[];if(!window.preMwEmbedConfig)window.preMwEmbedConfig={};if(!mw.setConfig)mw.setConfig=function(i,a){if(typeof a!="undefined")window.preMwEmbedConfig[i]=a;else if(typeof i=="object")for(var b in i)window.preMwEmbedConfig[b]=i[b]};
if(!mw.getConfig)mw.getConfig=function(i,a){return typeof window.preMwEmbedConfig[i]=="undefined"?typeof a!="undefined"?a:null:window.preMwEmbedConfig[i]};if(!mw.versionIsAtLeast)mw.versionIsAtLeast=function(i,a){if(typeof a=="undefined")a=window.MWEMBED_VERSION;for(var b=i.split("."),c=a.split("."),d=0;d<b.length;d++){if(parseInt(c[d])>parseInt(b[d]))break;if(parseInt(c[d])<parseInt(b[d]))return!1}return!0};if(!mw.ready)mw.ready=function(i){window.preMwEmbedReady.push(i)};
mw.getKalturaThumbUrl=function(i){kWidget.log("mw.getKalturaThumbUrl is deprecated. Please use kWidget.getKalturaThumbUrl");return kWidget.getKalturaThumbUrl(i)};kWidget.getUserAgentPlayerRulesMsg=function(i){return kWidget.checkUserAgentPlayerRules(i,!0)};
kWidget.checkUserAgentPlayerRules=function(i){var a=mw.getConfig("KalturaSupport_ForceUserAgent")?mw.getConfig("KalturaSupport_ForceUserAgent"):navigator.userAgent,b={mode:"flash",val:!0};if(!i.rules)return b;for(var c in i.rules){var d=i.rules[c];if(d.match){if(a.indexOf(d.match)!==-1)return i.actions&&i.actions[c]?i.actions[c]:b}else if(d.regMatch&&(d=d.regMatch.replace(/(^\/)|(\/$)/g,""),RegExp(d).test(a)))return i.actions&&i.actions[c]?i.actions[c]:b}return b};
(function(i){i.seconds2npt=function(a,b){if(isNaN(a))return i.log("Warning: mediawiki.UtilitiesTime, trying to get npt time on NaN:"+a),"0:00:00";var c=i.seconds2Measurements(a);c.seconds=b?Math.round(c.seconds*1E3)/1E3:Math.round(c.seconds);if(c.seconds<10)c.seconds="0"+c.seconds;if(c.hours==0)hoursStr="";else{if(c.minutes<10)c.minutes="0"+c.minutes;hoursStr=c.hours+":"}return hoursStr+c.minutes+":"+c.seconds};i.npt2seconds=function(a){if(!a)return 0;var a=a.replace(/npt:|s/g,""),b=0,c=0,d=0;times=
a.split(":");times.length==3?(d=times[2],c=times[1],b=times[0]):times.length==2?(d=times[1],c=times[0]):d=times[0];d=d.replace(/,\s?/,".");return parseInt(b*3600)+parseInt(c*60)+parseFloat(d)};i.seconds2Measurements=function(a){var b={};b.days=Math.floor(a/86400);b.hours=Math.floor(Math.round(a)/3600);b.minutes=Math.floor(Math.round(a)/60%60);b.seconds=a%60;return b}})(window.kWidget);
(function(i){if(!i)i=window.kWidget={};i.api=function(a){return this.init(a)};i.api.prototype={ks:null,type:"auto",baseParam:{apiVersion:"3.1",expiry:"86400",clientTag:"kwidget:v"+window.MWEMBED_VERSION,format:9,ignoreNull:1},init:function(a){for(var b in a)this[b]=a[b];if(!this.serviceUrl)this.serviceUrl=mw.getConfig("Kaltura.ServiceUrl");if(!this.serviceBase)this.serviceBase=mw.getConfig("Kaltura.ServiceBase");if(!this.statsServiceUrl)this.statsServiceUrl=mw.getConfig("Kaltura.StatsServiceUrl");
if(typeof this.disableCache=="undefined")this.disableCache=mw.getConfig("Kaltura.NoApiCache")},setKs:function(a){this.ks=a},getKs:function(){return this.ks},doRequest:function(a,b){var c={};this.disableCach===!0&&(c.nocache="true");for(var d in this.baseParam)typeof c[d]=="undefined"&&(c[d]=this.baseParam[d]);a.service!="user"?$.extend(c,this.handleKsServiceRequest(a)):$.extend(c,a);c.kalsig=this.hashCode($.param(c));d=c.service;delete c.service;var e=function(a){a.length==2&&c["1:service"]=="session"&&
(a=a[1]);b&&(b(a),b=null)};try{c.format=1,this.xhrRequest(this.getApiUrl(d),c,function(a){e(a)})}catch(g){c.format=9;d=this.getApiUrl(d)+"&"+$.param(c);var h="kapi_"+Math.abs(this.hashCode($.param(c)));window[h]&&(this.callbackIndex++,h+=this.callbackIndex);window[h]=function(a){e(a);window[h]=void 0;try{delete window[h]}catch(b){}};d+="&callback="+h;i.appendScriptUrl(d)}},xhrRequest:function(a,b,c){this[this.type=="auto"?$.param(b).length>2E3?"xhrPost":"xhrGet":this.type=="GET"?"xhrGet":"xhrPost"](a,
b,c)},xhrGet:function(a,b,c){var d=new XMLHttpRequest;d.onreadystatechange=function(){d.readyState==4&&d.status==200&&c(JSON.parse(d.responseText))};d.open("GET",a+"&"+$.param(b),!0);d.send()},xhrPost:function(a,b,c){var d=new XMLHttpRequest;d.onreadystatechange=function(){d.readyState==4&&d.status==200&&c(JSON.parse(d.responseText))};d.open("POST",a,!0);d.setRequestHeader("Content-type","application/x-www-form-urlencoded");d.send($.param(b))},handleKsServiceRequest:function(a){var b={};if(a.ks)this.ks=
a.ks;!a.length&&!this.getKs()&&(a=[a]);if(a.length){b.service="multirequest";b.action="null";var c=1;if(!this.getKs())b[c+":service"]="session",b[c+":action"]="startWidgetSession",b[c+":widgetId"]=this.wid,c=2;for(var d=0;d<a.length;d++){var e=c+d;b[e+":ks"]=this.getKs()?this.getKs():"{1:result:ks}";for(var g in a[d])if(typeof a[d][g]=="object")for(var h in a[d][g])b[e+":"+g+":"+h]=a[d][g][h];else b[e+":"+g]=a[d][g]}}else b=a,b.ks=this.getKs();return b},getApiUrl:function(a){var b=this.serviceUrl;
if(a&&a=="stats"&&this.statsServiceUrl)b=this.statsServiceUrl;return b+this.serviceBase+a},hashCode:function(a){var b=0;if(a.length==0)return b;for(var c=0;c<a.length;c++){var d=a.charCodeAt(c),b=(b<<5)-b+d;b&=b}return b}}})(window.kWidget);mw.setConfig("debug",!1);mw.setConfig("Mw.XmlProxyUrl","http://cdnbakmi.kaltura.com/html5/html5lib/v1.8.3.1/simplePhpXMLProxy.php");mw.setConfig("Kaltura.UseManifestUrls",!0);mw.setConfig("Kaltura.Protocol","http");mw.setConfig("Kaltura.ServiceUrl","http://cdnapi.kaltura.com");
mw.setConfig("Kaltura.ServiceBase","/api_v3/index.php?service=");mw.setConfig("Kaltura.CdnUrl","http://cdnbakmi.kaltura.com");mw.setConfig("Kaltura.StatsServiceUrl","http://stats.kaltura.com");mw.setConfig("Kaltura.IframeRewrite",!0);mw.setConfig("EmbedPlayer.EnableIpadHTMLControls",!0);mw.setConfig("EmbedPlayer.UseFlashOnAndroid",!0);mw.setConfig("Kaltura.LoadScriptForVideoTags",!0);mw.setConfig("Kaltura.AllowIframeRemoteService",!0);mw.setConfig("Kaltura.UseAppleAdaptive",!0);
mw.setConfig("Kaltura.EnableEmbedUiConfJs",!1);mw.setConfig("Kaltura.PageGoogleAalytics",!1);kWidget.inLoaderUiConfJsCallback();kWidget.setup();mw.setConfig("EmbedPlayer.FullScreenZIndex",100000010);mw.setConfig("Kaltura.UseFlavorIdsUrls",!1);var ua=navigator.userAgent;/(iPhone|iPod|iPad)/i.test(ua)&&(/OS [2-4]_\d(_\d)? like Mac OS X/i.test(ua)||/CPU like Mac OS X/i.test(ua))&&mw.setConfig("Kaltura.UseAppleAdaptive",!1);
function DisneyPlayer(i,a){function b(a,b,f){if(disneyPlayerResources[a])f!=null&&(e(a)?setTimeout(f,0):disneyPlayerResources[a].callbacks.push(f));else{var g;if(b=="js")g=document.createElement("script"),g.type="text/javascript",g.src=a,g.readyState?g.onreadystatechange=function(){if(g.readyState=="loaded"||g.readyState=="complete")g.onreadystatechange=null,d(a)}:g.onload=function(){g.onload=null;d(a)};else if(b=="css")g=document.createElement("link"),g.rel="stylesheet",g.type="text/css",g.href=
a,setTimeout(c,1);else return;b={};b.callbacks=[f];b.loaded=!1;b.element=g;disneyPlayerResources[a]=b;document.getElementsByTagName("head")[0].appendChild(g)}}function c(){for(var a=document.styleSheets,b=0;b<a.length;b++){var f=a[b];(f=f.ownerNode?f.ownerNode:f.owningElement)&&disneyPlayerResources[f.href]&&!e(f.href)&&d(f.href)}setTimeout(c,1)}function d(a){disneyPlayerResources[a].loaded=!0;for(var a=disneyPlayerResources[a].callbacks,b=0;b<a.length;b++){var c=a[b];c&&typeof c=="function"&&c()}}
function e(a){return!!disneyPlayerResources[a]&&disneyPlayerResources[a].loaded}function g(){E++}function h(){E>=2&&(E=0,setTimeout(f.controls.replay,0))}function j(a){typeof console!="undefined"&&console.log&&console.log(a)}function k(){if(e(t(G))&&e(t(H))&&typeof z=="undefined"){var a=document.getElementById(f.id);u(a).addClass(F+"-playlist-enabled");a=document.getElementById(f.id+"_player_layout");z=new Playlist(f.playerConfiguration.playerId+"_playlist",{playlistId:f.playerConfiguration.playlistId,
orientation:F,widgetId:f.kalturaConfiguration.widgetId,playlistSize:f.playerConfiguration.playlistSize,sponsorMessage:f.ads.sponsorMessage},a)}}function o(){return y[f.playerConfiguration.playerSize]!=null}function s(){if(kWidget.isHTML5FallForward()){var a=document.getElementById(f.id);u(a).removeClass("layout")}}function D(){if(kWidget.isHTML5FallForward()){var a=document.getElementById(f.id);u(a).addClass("layout")}}function n(){f.removeMessageListener("mediaReady",n)}function r(){if(m=document.getElementById(f.embedConfiguration.id))if(m.addJsListener){A=
!0;for(var a=0;a<q.length;a++)(listener=q[a])&&m.addJsListener(listener.name,listener.listenerName);f.addMessageListener("openFullScreen",s);f.addMessageListener("closeFullScreen",D);f.addMessageListener("mediaReady",n);z&&z.setPlayer(m);f.sendMessage("disneyPlayerReady",f.id)}else j("Can't add listeners for "+f.embedConfiguration.id);else j("Can't find player element for "+f.embedConfiguration.id)}function x(a){var b=0;if(!(a.loginstatus==="Guest Not Logged In"||a.loginstatus==="Anonymous Guest"))a.birthyear!==
null?(b=a.birthyear,b=(new Date).getFullYear()-b,b=--b,b<13?v="child":a.age>=18?v="adult":v="teen"):a.age===null||a.age<13?v="child":a.age>=18?v="adult":v="teen",v==="child"&&(f.kalturaConfiguration["DoubleClick.customParams"]+="%26age%3Dchild")}function p(){var a="//globalregsession.go.com/globalregsession/session?as="+DisneyPlayerUtil.getGlobalCallback(f.id,x),b=function(){l()};(a=u.getScript(a,function(){l()}))&&a.fail&&a.fail(b)}function l(){f.playerConfiguration.mode=="html"&&mw.setConfig("forceMobileHTML5",
!0);var a=document.getElementById(f.id),c=u(a);c.addClass("video");c.addClass("layout");var d="player layout";o&&(c.addClass(f.playerConfiguration.playerSize),d+=" "+f.playerConfiguration.playerSize);a.innerHTML="<div id='"+f.id+"_player_layout' class='"+d+"'><div id='"+f.embedConfiguration.id+"'></div></div>";kWidget.embed({targetId:f.embedConfiguration.id,id:f.embedConfiguration.id,wid:f.kalturaConfiguration.widgetId,uiconf_id:f.kalturaConfiguration.uiConfId,entry_id:f.kalturaConfiguration.entryId,
src:f.embedConfiguration.resource,width:f.embedConfiguration.width,height:f.embedConfiguration.height,params:{wmode:f.embedConfiguration.wmode},flashvars:f.kalturaConfiguration,readyCallback:DisneyPlayerUtil.jsCallbackReady});if(f.playerConfiguration.playlist&&f.playerConfiguration.playlist!="none")a=f.playerConfiguration.playlist,a!="none"&&(F=a,b(t(G),"css",k),b(t(H),"js",k))}function B(a){return(a=RegExp("[?&]"+a+"=([^&]*)").exec(window.location.search))&&decodeURIComponent(a[1].replace(/\+/g,
" "))}function C(a,b,c){var c=c||{},b=b||{},d;for(d in b)a[d]||(a[d]=c[d]?c[d]:b[d])}function t(a){return document.location.protocol+"//"+I+"/player/"+f.playerConfiguration.playerVersion+a}var u=jQuery,I=document.location.protocol=="https:"?"secure.vp.disney.go.com":"vp.disney.go.com",J=document.location.protocol=="https:"?"www.kaltura.com":"cdnapi.kaltura.com",G="/html5/plugins/css/playlist.css",H="/html5/plugins/js/playlist.min.js",K=document.location.protocol+"//"+J+"/index.php/partnerservices2/executeplaylist?uid=&format=8",
w={playerId:"6607922",accountId:"628012",mode:"flash",playerSize:"M",playlist:"none",playerVersion:"latest"},y={XL:{width:"768",height:"432"},L:{width:"640",height:"360"},M:{width:"512",height:"288"},S:{width:"384",height:"216"},XS:{width:"256",height:"144"}},L={id:"kaltura_player",name:"kaltura_player",type:"application/x-shockwave-flash",allowFullScreen:"true",allowNetworking:"all",allowScriptAccess:"always",height:y[w.playerSize].width,width:y[w.playerSize].height,bgcolor:"#000000",rel:"media:video",
wmode:"transparent"},M={sourceType:"entryId",host:J,"statistics.statsDomain":"stats.kaltura.com",clientDefaultMethod:"GET",uiConfId:w.playerId,widgetId:"_"+w.accountId,partnerId:w.accountId,subpId:w.accountId,streamerUrl:"rtmp://rtmp.kaltura.com/ondemand/",streamerType:"auto",externalInterfaceDisabled:"false"},f=this,m,F="horizontal",z,A=!1,q=[],E=0,v="";this.playerConfiguration={};this.playerConfiguration.disablePlugin=function(a){f.kalturaConfiguration[a+".loadingPolicy"]="onDemand";f.kalturaConfiguration[a+
".disableHTML5"]="true";f.kalturaConfiguration[a+".position"]="lastChild";f.kalturaConfiguration[a+".relativeTo"]="PlayerHolder";f.kalturaConfiguration[a+".asyncInit"]="false"};this.kalturaConfiguration={};this.embedConfiguration={};this.id="";this.controls={};this.ads={};this.ads.sponsorMessage="";this.info={getMetadata:function(){return m?m.evaluate("{mediaProxy.entryMetadata}"):{}}};DisneyPlayer.prototype.createPlayer=function(a,c){if(a){if(kWidget.isHTML5FallForward())window.kalturaDynamicEmbed=
!0;f.id=a;C(f.playerConfiguration,c);DisneyPlayerUtil.addReadyHandler(f.id,r);if(window.location.href.indexOf("/cds/")!=-1)f.playerConfiguration.cdsMode="true";var d=B("entryId");if(d&&d!="")f.playerConfiguration.entryId=d;if((d=B("playerId"))&&d!="")f.playerConfiguration.playerId=d;if((d=B("playerVersion"))&&d!="")f.playerConfiguration.playerVersion=d;if((d=B("accountId"))&&d!="")f.kalturaConfiguration.widgetId="_"+d,f.kalturaConfiguration.partnerId=d,f.kalturaConfiguration.subpId=d;d=[];if(window.location.href.indexOf("disney.com")===
-1&&window.location.href.indexOf("disney.go.com")===-1){var e=[],i=document.cookie.indexOf("asi_segs=");if(i>=0&&(i=document.cookie.indexOf("=",i)+1,i>0)){e=document.cookie.indexOf(";",i);if(e==-1)e=document.cookie.length;e=document.cookie.substring(i,e).split("|")}if(e==null||e.length==0)e="null";if(typeof e!=="undefined"&&e[0]){for(var i="asi%3D"+e[0],j=1;j<e.length;j++)i+="%2C"+e[j];d.push(i)}}f.playerConfiguration.playlistId&&d.push("videoPlaylistId%3D"+f.playerConfiguration.playlistId);if(!(d.length<=
0)){f.kalturaConfiguration["DoubleClick.customParams"]=d[0];for(j=1;j<d.length;j++)f.kalturaConfiguration["DoubleClick.customParams"]+="%26"+d[j]}C(f.playerConfiguration,w);f.kalturaConfiguration.cdnHost=I+"/player/"+f.playerConfiguration.playerVersion+"/";f.kalturaConfiguration.pluginDomain=t("/flash/plugins/");C(f.kalturaConfiguration,M,f.playerConfiguration);f.embedConfiguration.id=f.id+"_player";f.embedConfiguration.name=f.id+"_player";C(f.embedConfiguration,L,f.playerConfiguration);for(var k in f.playerConfiguration)switch(d=
f.playerConfiguration[k],k){case "playlistId":e=K;e+="&partner_id="+f.kalturaConfiguration.partnerId;e+="&subp_id="+f.kalturaConfiguration.subpId;e+="&playlist_id="+d;f.kalturaConfiguration["playlistAPI.kpl0Url"]=encodeURIComponent(e);if(f.playerConfiguration.entryId)f.kalturaConfiguration["playlistAPI.initItemEntryId"]=f.playerConfiguration.entryId;break;case "playlistURL":f.kalturaConfiguration["playlistAPI.kpl0Url"]=encodeURIComponent(d);break;case "playerId":f.kalturaConfiguration.uiConfId=d;
break;case "playerSize":if(o()){f.embedConfiguration.width=y[d].width;f.embedConfiguration.height=y[d].height;if(f.playerConfiguration.playlistSize==null)f.playerConfiguration.playlistSize=d;switch(d){case "S":case "XS":f.kalturaConfiguration["MediaDescription.loadingPolicy"]="onDemand",f.kalturaConfiguration["MediaDescription.disableHTML5"]="true",f.kalturaConfiguration["MediaControlbar.showShortTitle"]="false",f.kalturaConfiguration["MediaControlbar.showBufferBar"]="false",f.kalturaConfiguration["onVideoPlayBtnStartScreen.visible"]=
"false"}}else e=d.toLowerCase().indexOf("x"),f.embedConfiguration.width=d.slice(0,e),f.embedConfiguration.height=d.slice(e+1);break;case "entryid":case "entryID":case "entryId":f.kalturaConfiguration.entryId=d;break;case "accountId":f.kalturaConfiguration.widgetId="_"+d;f.kalturaConfiguration.partnerId=d;f.kalturaConfiguration.subpId=d;break;case "autoPlay":d=d.toString()=="true";f.kalturaConfiguration.autoPlay=d.toString();f.kalturaConfiguration["playlistAPI.autoPlay"]=d.toString();break;case "showReplayButton":d.toString()==
"true"&&(f.addMessageListener("playerPlayEnd",g),f.addMessageListener("playerPlayed",h));break;case "cdsMode":d.toString()=="true"&&f.playerConfiguration.disablePlugin("DoubleClick");break;case "ads.sponsorMessage":f.ads.sponsorMessage=d;break;case "loop":f.kalturaConfiguration.loop=d,f.kalturaConfiguration["playlistAPI.loop"]=d}if(f.ads.sponsorMessage!="")f.kalturaConfiguration["MediaControlbar.sponsorMessage"]=f.ads.sponsorMessage,f.kalturaConfiguration["MediaDescription.sponsorMessage"]=f.ads.sponsorMessage;
k=t("/flash/kdp3.swf")+"?/cache_st/0/wid/"+f.kalturaConfiguration.widgetId+"/uiconf_id/"+f.kalturaConfiguration.uiConfId;f.embedConfiguration.resource=k;f.embedConfiguration.data=k;f.embedConfiguration.movie=k;b(t("/html5/plugins/css/player.css"),"css",p)}};this.controls.play=function(){f.sendMessage("doPlay")};this.controls.pause=function(){f.sendMessage("doPause")};this.controls.replay=function(){m&&m.setKDPAttribute&&(m.setKDPAttribute("playlistAPI.dataProvider","selectedIndex",0),f.sendMessage("doSeek",
0),f.sendMessage("doPlay"))};DisneyPlayer.prototype.loadMedia=function(a){f.sendMessage("changeMedia",{entryId:a})};DisneyPlayer.prototype.sendMessage=function(a,b){m&&m.sendNotification&&m.sendNotification(a,b)};DisneyPlayer.prototype.addMessageListener=function(a,b){var c=f.id+"_"+a+"_"+Math.round(Math.random()*1E6);q.push({name:a,callback:b,listenerName:c});window[c]=b;A&&m&&m.addJsListener&&m.addJsListener(a,c)};DisneyPlayer.prototype.removeMessageListener=function(a,b){for(var c=0;c<q.length;c++){var d=
q[c];if(d&&d.name==a&&d.callback==b)d=d.listenerName,A&&m&&m.removeJsListener&&m.removeJsListener(a,d),window[d]=null,q[c]=null}};DisneyPlayer.prototype.destroy=function(){var a=document.getElementById(f.id),a=u(a);a.removeClass("video");a.removeClass("layout");a.removeClass(f.playerConfiguration.playerSize);a=document.getElementById(f.id+"_player_layout");a=u(a);a.removeClass("player");a.removeClass("layout");a.removeClass(f.playerConfiguration.playerSize);for(a=0;a<q.length;a++){var b=q[a];if(b)b=
b.listenerName,A&&m&&m.removeJsListener&&m.removeJsListener(name,b),window[b]=null,q[a]=null}f.sendMessage("cleanMedia");f.sendMessage("doPause");f.sendMessage("doStop");kWidget.destroy(f.embedConfiguration.id);m=null};typeof disneyPlayerResources==="undefined"&&(disneyPlayerResources={});if(typeof DisneyPlayerUtil==="undefined")DisneyPlayerUtil={callbacks:[],globalCallbacks:{}},DisneyPlayerUtil.jsCallbackReady=function(a){j("player id is ready: "+a);for(var b=0;b<DisneyPlayerUtil.callbacks.length;b++)DisneyPlayerUtil.callbacks[b].id==
a&&setTimeout(DisneyPlayerUtil.callbacks[b].callback,0)},DisneyPlayerUtil.addReadyHandler=function(a,b){DisneyPlayerUtil.callbacks.push({id:a+"_player",callback:b})},DisneyPlayerUtil.removeReadyHandler=function(a,b){for(var c=0;c<DisneyPlayerUtil.callbacks.length;c++)(b=DisneyPlayerUtil.callbacks[c])&&b.id==a&&b.callback==b&&(DisneyPlayerUtil.callbacks[c]=null)},DisneyPlayerUtil.getGlobalCallback=function(a,b){DisneyPlayerUtil.globalCallbacks[a]=b;return"DisneyPlayerUtil.globalCallbacks."+a};f.createPlayer(i,
a)};